{{- $component := "analyzer" -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "enterprise.analyzer.fullname" . }}
  labels:
    {{- include "enterprise.labels" (merge (dict "component" $component) .) | indent 4 }}
  annotations:
    {{- include "enterprise.annotations" (merge (dict "component" $component) .) | indent 4 }}
data:
  analyzer_config.yaml: |
{{- with .Values.analyzer.configFile }}
    {{- toYaml . | nindent 4 }}
{{- end }}