{{- $component := "analyzer" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "enterprise.analyzer.fullname" . }}
  labels:
    app: {{ template "enterprise.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ $component }}
    {{- with .Values.anchoreAnalyzer.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "enterprise.fullname" . }}
      component: {{ $component }}
  replicas: {{ .Values.anchoreAnalyzer.replicaCount }}
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        app: {{ template "enterprise.fullname" . }}
        component: {{ $component }}
        {{- with .Values.anchoreAnalyzer.labels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.labels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      annotations:
      {{- with .Values.annotations }}
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.anchoreAnalyzer.annotations }}
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.inject_secrets_via_env }}
        checksum/secrets: {{ include (print $.Template.BasePath "/engine_secret.yaml") . | sha256sum }}
      {{- end }}
        checksum/env: {{ include (print $.Template.BasePath "/engine_configmap_env.yaml") . | sha256sum }}
        checksum/engine-config: {{ include (print $.Template.BasePath "/engine_configmap.yaml") . | sha256sum }}
        checksum/analyzer-config: {{ include (print $.Template.BasePath "/analyzer_configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.securityContext }}
      securityContext:
        {{ toYaml . | nindent 8 }}
      {{- end }}
    {{- if .Values.anchoreEnterpriseGlobal.enabled }}
      imagePullSecrets:
      - name: {{ .Values.anchoreEnterpriseGlobal.imagePullSecretName }}
    {{- else }}
      {{- with .Values.imagePullSecretName }}
      imagePullSecrets:
      - name: {{ . }}
      {{- end }}
    {{- end }}
    {{- if and .Values.scratchVolume.fixGroupPermissions .Values.securityContext.fsGroup }}
      initContainers:
        - name: mode-fixer
          image: alpine
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: {{ $component }}-scratch
              mountPath: {{ .Values.scratchVolume.mountPath }}
          command:
            - sh
            - -c
            - (chmod 0775 {{ .Values.scratchVolume.mountPath }}; chgrp {{ .Values.securityContext.fsGroup }} {{ .Values.scratchVolume.mountPath }} )
      {{- end }}
      containers:
      {{- if .Values.cloudsql.enabled  }}
      - name: cloudsql-proxy
        image: {{ .Values.cloudsql.image.repository }}:{{ .Values.cloudsql.image.tag }}
        imagePullPolicy: {{ .Values.cloudsql.image.pullPolicy }}
        command: ["/cloud_sql_proxy"]
        args:
        - "-instances={{ .Values.cloudsql.instance }}=tcp:5432"
        {{- if .Values.cloudsql.useExistingServiceAcc }}
        - "-credential_file=/var/{{ .Values.cloudsql.serviceAccSecretName }}/{{ .Values.cloudsql.serviceAccJsonName }}"
        volumeMounts:
        - mountPath: /var/{{ .Values.cloudsql.serviceAccSecretName }}
          name: {{ .Values.cloudsql.serviceAccSecretName }}
          readOnly: true
        {{- end }}
      {{- end }}
      - name: {{ .Chart.Name }}-{{ $component }}
        {{- if .Values.anchoreEnterpriseGlobal.enabled }}
        image: {{ .Values.anchoreEnterpriseGlobal.image }}
        imagePullPolicy: {{ .Values.anchoreEnterpriseGlobal.imagePullPolicy }}
        {{- else }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{- end }}
        {{- if .Values.anchoreEnterpriseGlobal.enabled }}
        args: ["anchore-enterprise-manager", "service", "start", "--no-auto-upgrade", "analyzer"]
        {{- else }}
        args: ["anchore-manager", "service", "start", "--no-auto-upgrade", "analyzer"]
        {{- end }}
        envFrom:
        {{- if not .Values.inject_secrets_via_env }}
        {{- if .Values.existingSecret }}
        - secretRef:
            name: {{ .Values.existingSecret }}
        {{- else }}
        - secretRef:
            name: {{ include "enterprise.fullname" . }}
        - secretRef:
            name: {{ print (include "enterprise.fullname" .) "-admin-pass" }}
        {{- end }}
        {{- end }}
        - configMapRef:
            name: {{ template "enterprise.fullname" . }}-env
        env:
        {{- with .Values.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.anchoreAnalyzer.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: ANCHORE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - name: analyzer-api
          containerPort: {{ .Values.anchoreAnalyzer.containerPort }}
        volumeMounts:
        {{- if .Values.anchoreEnterpriseGlobal.enabled }}
        - name: anchore-license
          mountPath: /home/anchore/license.yaml
          subPath: license.yaml
        {{- end }}
        - name: analyzer-config-volume
          mountPath: {{ .Values.serviceDir }}/analyzer_config.yaml
          subPath: analyzer_config.yaml
        - name: config-volume
          mountPath: /config/config.yaml
          subPath: config.yaml
        {{- if (.Values.certStoreSecretName) }}
        - name: certs
          mountPath: /home/anchore/certs/
          readOnly: true
        {{- end }}
        - name: {{ $component }}-scratch
          mountPath: {{ .Values.scratchVolume.mountPath }}
        {{- if .Values.openShiftDeployment }}
        - name: service-config-volume
          mountPath: /anchore_service_config
        - name: logs
          mountPath: /var/log/anchore
        - name: run
          mountPath: /var/run/anchore
        {{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: analyzer-api
            {{- if .Values.internalServicesSsl.enabled }}
            scheme: HTTPS
            {{- end }}
          initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
          periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          successThreshold: {{ .Values.probes.liveness.successThreshold }}
        readinessProbe:
          httpGet:
            path: /health
            port: analyzer-api
            {{- if .Values.internalServicesSsl.enabled }}
            scheme: HTTPS
            {{- end }}
          timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          successThreshold: {{ .Values.probes.readiness.successThreshold }}
        resources:
          {{ toYaml .Values.anchoreAnalyzer.resources | nindent 10 }}
      volumes:
        {{- if .Values.anchoreEnterpriseGlobal.enabled }}
        - name: anchore-license
          secret:
            secretName: {{ .Values.anchoreEnterpriseGlobal.licenseSecretName }}
        {{- end }}
        - name: config-volume
          configMap:
            name: {{ template "enterprise.fullname" .}}
        - name: {{ $component }}-scratch
          {{ toYaml .Values.scratchVolume.details | nindent 10 }}
        - name: analyzer-config-volume
          configMap:
            name: {{ template "enterprise.analyzer.fullname" . }}
        {{- if .Values.openShiftDeployment }}
        - name: service-config-volume
          emptyDir: {}
        - name: logs
          emptyDir: {}
        - name: run
          emptyDir: {}
        {{- end }}
        {{- with .Values.certStoreSecretName }}
        - name: certs
          secret:
            secretName: {{ . }}
        {{- end }}
        {{- if .Values.cloudsql.useExistingServiceAcc }}
        - name: {{ .Values.cloudsql.serviceAccSecretName }}
          secret:
            secretName: {{ .Values.cloudsql.serviceAccSecretName }}
        {{- end }}
      {{- with .Values.anchoreAnalyzer.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.anchoreAnalyzer.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.anchoreAnalyzer.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serviceAccountName }}
      serviceAccountName: {{ . }}
      {{- end }}
