{{- $component := "analyzer" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "enterprise.analyzer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "enterprise.labels" (merge (dict "component" $component) .) | indent 4 }}
  annotations:
    {{- include "enterprise.annotations" (merge (dict "component" $component) .) | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "enterprise.fullname" . }}
      app.kubernetes.io/component: {{ $component }}
  replicas: {{ .Values.analyzer.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "enterprise.labels" (merge (dict "component" $component) .) | indent 8 }}
      annotations:
        {{- include "enterprise.annotations" (merge (dict "component" $component) .) | indent 8 }}
      {{- if not .Values.inject_secrets_via_env }}
        checksum/secrets: {{ include (print $.Template.BasePath "/engine_secret.yaml") . | sha256sum }}
      {{- end }}
        checksum/env: {{ include (print $.Template.BasePath "/engine_configmap_env.yaml") . | sha256sum }}
        checksum/engine-config: {{ include (print $.Template.BasePath "/engine_configmap.yaml") . | sha256sum }}
        checksum/analyzer-config: {{ include (print $.Template.BasePath "/analyzer_configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.securityContext }}
      securityContext:
        {{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.serviceAccountName }}
      serviceAccountName: {{ . }}
    {{- end }}
    {{- with .Values.imagePullSecretName }}
      imagePullSecrets:
      - name: {{ . }}
    {{- end }}
    {{- if and .Values.scratchVolume.fixGroupPermissions .Values.securityContext.fsGroup }}
      initContainers:
        - name: mode-fixer
          image: alpine
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: "{{ $component }}-scratch"
              mountPath: {{ .Values.scratchVolume.mountPath }}
          command:
            - sh
            - -c
            - (chmod 0775 {{ .Values.scratchVolume.mountPath }}; chgrp {{ .Values.securityContext.fsGroup }} {{ .Values.scratchVolume.mountPath }} )
    {{- end }}
      containers:
      - name: "{{ .Chart.Name }}-{{ $component }}"
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args: ["anchore-enterprise-manager", "service", "start", "--no-auto-upgrade", "analyzer"]
        envFrom:
        - configMapRef:
            name: "{{ template "enterprise.fullname" . }}-env"
    {{- if not .Values.inject_secrets_via_env }}
      {{- if .Values.existingSecret }}
        - secretRef:
            name: {{ .Values.existingSecret }}
      {{- else }}
        - secretRef:
            name: {{ template "enterprise.fullname" . }}
        - secretRef:
            name: "{{ template "enterprise.fullname" . }}-admin-pass"
      {{- end }}
    {{- end }}
        env:
        {{- include "enterprise.environment" (merge (dict "component" $component) .) | indent 8 }}
        - name: ANCHORE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - name: analyzer-api
          containerPort: {{ .Values.analyzer.containerPort }}
        volumeMounts:
        - name: anchore-license
          mountPath: /home/anchore/license.yaml
          subPath: license.yaml
        - name: analyzer-config-volume
          mountPath: "{{ .Values.serviceDir }}/analyzer_config.yaml"
          subPath: analyzer_config.yaml
        - name: config-volume
          mountPath: /config/config.yaml
          subPath: config.yaml
        - name: "{{ $component }}-scratch"
          mountPath: {{ .Values.scratchVolume.mountPath }}
      {{- if (.Values.certStoreSecretName) }}
        - name: certs
          mountPath: /home/anchore/certs/
          readOnly: true
      {{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: analyzer-api
          {{- if .Values.internalServicesSsl.enabled }}
            scheme: HTTPS
          {{- end }}
          initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
          periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          successThreshold: {{ .Values.probes.liveness.successThreshold }}
        readinessProbe:
          httpGet:
            path: /health
            port: analyzer-api
          {{- if .Values.internalServicesSsl.enabled }}
            scheme: HTTPS
          {{- end }}
          timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          successThreshold: {{ .Values.probes.readiness.successThreshold }}
      {{- with .Values.analyzer.resources }}
        resources:
          {{ toYaml . | indent 10 }}
      {{- end }}
    {{- if .Values.cloudsql.enabled  }}
      - name: cloudsql-proxy
        image: "{{ .Values.cloudsql.image.repository }}:{{ .Values.cloudsql.image.tag }}"
        imagePullPolicy: {{ .Values.cloudsql.image.pullPolicy }}
        command: ["/cloud_sql_proxy"]
        args:
        - "-instances={{ .Values.cloudsql.instance }}=tcp:5432"
      {{- if .Values.cloudsql.useExistingServiceAcc }}
        - "-credential_file=/var/{{ .Values.cloudsql.serviceAccSecretName }}/{{ .Values.cloudsql.serviceAccJsonName }}"
        volumeMounts:
        - mountPath: "/var/{{ .Values.cloudsql.serviceAccSecretName }}"
          name: {{ .Values.cloudsql.serviceAccSecretName }}
          readOnly: true
      {{- end }}
    {{- end }}
      volumes:
        - name: anchore-license
          secret:
            secretName: {{ .Values.licenseSecretName }}
        - name: config-volume
          configMap:
            name: {{ template "enterprise.fullname" . }}
        - name: "{{ $component }}-scratch"
          {{ toYaml .Values.scratchVolume.details | indent 10 }}
        - name: analyzer-config-volume
          configMap:
            name: {{ template "enterprise.analyzer.fullname" . }}
      {{- with .Values.certStoreSecretName }}
        - name: certs
          secret:
            secretName: {{ . }}
      {{- end }}
      {{- if .Values.cloudsql.useExistingServiceAcc }}
        - name: {{ .Values.cloudsql.serviceAccSecretName }}
          secret:
            secretName: {{ .Values.cloudsql.serviceAccSecretName }}
      {{- end }}
    {{- with .Values.analyzer.nodeSelector }}
      nodeSelector:
        {{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.analyzer.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.analyzer.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
    {{- end }}
