{{- if not .Values.anchoreGlobal.existingSecret }}

{{- $anchoreAdminPass := (include "enterprise.defaultAdminPassword" . | quote) }}

{{- /*
  If release is being upgraded, don't recreate the defaultAdminPassword, instead get it from the corresponding existing
  secret. For users upgrading to chart v1.12.5 or higher, use the new admin-password secret, otherwise use the old
  engine secret.
*/ -}}
{{- if and .Release.IsUpgrade (not .Values.anchoreGlobal.defaultAdminPassword) }}
{{- $adminPassSecret := (lookup "v1" "Secret" .Release.Namespace (print (include "enterprise.fullname" .) "-admin-pass")) }}
{{- $engineSecret := (lookup "v1" "Secret" .Release.Namespace (include "enterprise.fullname" . )) -}}
{{- if or $engineSecret $adminPassSecret }}
{{- $secret := (default $engineSecret $adminPassSecret) }}
{{- $anchoreAdminPass = (index $secret.data "ANCHORE_ADMIN_PASSWORD" | b64dec) }}
{{- end }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "enterprise.fullname" . }}-admin-pass
  labels:
    app: {{ template "enterprise.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.anchoreGlobal.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  ANCHORE_ADMIN_PASSWORD: {{ $anchoreAdminPass }}
{{- end }}
