{{- if not .Values.existingSecret -}}

{{- /*
  If release is being upgraded, don't recreate the defaultAdminPassword, instead get it from the corresponding existing
  secret. For users upgrading to chart v1.12.5 or higher, use the new admin-password secret, otherwise use the old
  engine secret.
*/ -}}
{{- $anchoreAdminPass := (include "enterprise.defaultAdminPassword" . | quote) -}}
{{- if and .Release.IsUpgrade (not .Values.defaultAdminPassword) -}}
  {{- $adminPassSecret := (lookup "v1" "Secret" .Release.Namespace (print (include "enterprise.fullname" .) "-admin-pass")) -}}
  {{- if $adminPassSecret -}}
    {{- $anchoreAdminPass = (index $adminPassSecret.data "ANCHORE_ADMIN_PASSWORD" | b64dec) -}}
  {{- end -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "enterprise.fullname" . }}-admin-pass
  labels:
    {{- include "enterprise.labels" . | indent 4 }}
  annotations:
    {{- include "enterprise.annotations" . | indent 4 }}
type: Opaque
stringData:
  ANCHORE_ADMIN_PASSWORD: {{ $anchoreAdminPass }}
{{- end }}
