{{- $component := "catalog" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "enterprise.catalog.fullname" . }}
  labels:
    app: {{ template "enterprise.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ $component }}
    {{- with .Values.anchoreCatalog.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "enterprise.fullname" . }}
      component: {{ $component }}
  replicas: {{ .Values.anchoreCatalog.replicaCount }}
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        app: {{ template "enterprise.fullname" . }}
        component: {{ $component }}
        {{- with .Values.anchoreCatalog.labels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.labels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      annotations:
      {{- with .Values.annotations }}
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.anchoreCatalog.annotations }}
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.inject_secrets_via_env }}
        checksum/secrets: {{ include (print $.Template.BasePath "/engine_secret.yaml") . | sha256sum }}
      {{- end }}
        checksum/env: {{ include (print $.Template.BasePath "/engine_configmap_env.yaml") . | sha256sum }}
        checksum/engine-config: {{ include (print $.Template.BasePath "/engine_configmap.yaml") . | sha256sum }}
      {{- if .Values.policyBundles }}
        checksum/policy-config: {{ include (print $.Template.BasePath "/policy_bundle_configmap.yaml") . | sha256sum }}
      {{- end }}
    spec:
      {{- with .Values.securityContext }}
      securityContext:
        {{ toYaml . | nindent 8 }}
      {{- end }}
    {{- if .Values.anchoreEnterpriseGlobal.enabled }}
      imagePullSecrets:
      - name: {{ .Values.anchoreEnterpriseGlobal.imagePullSecretName }}
    {{- else }}
      {{- with .Values.imagePullSecretName }}
      imagePullSecrets:
      - name: {{ . }}
      {{- end }}
    {{- end }}
      containers:
      {{- if .Values.cloudsql.enabled  }}
      - name: cloudsql-proxy
        image: {{ .Values.cloudsql.image.repository }}:{{ .Values.cloudsql.image.tag }}
        imagePullPolicy: {{ .Values.cloudsql.image.pullPolicy }}
        command: ["/cloud_sql_proxy"]
        args:
        - "-instances={{ .Values.cloudsql.instance }}=tcp:5432"
        {{- if .Values.cloudsql.useExistingServiceAcc }}
        - "-credential_file=/var/{{ .Values.cloudsql.serviceAccSecretName }}/{{ .Values.cloudsql.serviceAccJsonName }}"
        volumeMounts:
        - mountPath: /var/{{ .Values.cloudsql.serviceAccSecretName }}
          name: {{ .Values.cloudsql.serviceAccSecretName }}
          readOnly: true
        {{- end }}
      {{- end }}
      - name: {{ .Chart.Name }}-{{ $component }}
        {{- if .Values.anchoreEnterpriseGlobal.enabled }}
        image: {{ .Values.anchoreEnterpriseGlobal.image }}
        imagePullPolicy: {{ .Values.anchoreEnterpriseGlobal.imagePullPolicy }}
        {{- else }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{- end }}
        {{- if .Values.anchoreEnterpriseGlobal.enabled }}
        args: ["anchore-enterprise-manager", "service", "start", "--no-auto-upgrade", "catalog"]
        {{- else }}
        args: ["anchore-manager", "service", "start", "--no-auto-upgrade", "catalog"]
        {{- end }}
        envFrom:
        {{- if not .Values.inject_secrets_via_env }}
        {{- if .Values.existingSecret }}
        - secretRef:
            name: {{ .Values.existingSecret }}
        {{- else }}
        - secretRef:
            name: {{ include "enterprise.fullname" . }}
        - secretRef:
            name: {{ print (include "enterprise.fullname" .) "-admin-pass" }}
        {{- end }}
        {{- end }}
        - configMapRef:
            name: {{ template "enterprise.fullname" . }}-env
        env:
        {{- with .Values.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.anchoreCatalog.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: ANCHORE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - name: catalog
          containerPort: {{ .Values.anchoreCatalog.service.port }}
        volumeMounts:
        {{- if .Values.anchoreEnterpriseGlobal.enabled }}
        - name: anchore-license
          mountPath: /home/anchore/license.yaml
          subPath: license.yaml
        {{- end }}
        - name: config-volume
          mountPath: /config/config.yaml
          subPath: config.yaml
        {{- if .Values.policyBundles }}
        {{- range $key, $value := .Values.policyBundles }}
        - name: policy-bundle-volume
          mountPath: {{ $.Values.serviceDir  }}/bundles/{{ $key }}
          subPath: {{ $key }}
        {{- end }}
        {{- end }}
        {{- if .Values.openShiftDeployment }}
        - name: service-config-volume
          mountPath: /anchore_service_config
        - name: logs
          mountPath: /var/log/anchore
        - name: run
          mountPath: /var/run/anchore
        {{- end }}
        {{- if (.Values.certStoreSecretName) }}
        - name: certs
          mountPath: /home/anchore/certs/
          readOnly: true
        {{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: catalog
            {{- if .Values.internalServicesSsl.enabled }}
            scheme: HTTPS
            {{- end }}
          initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
          periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          successThreshold: {{ .Values.probes.liveness.successThreshold }}
        readinessProbe:
          httpGet:
            path: /health
            port: catalog
            {{- if .Values.internalServicesSsl.enabled }}
            scheme: HTTPS
            {{- end }}
          timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          successThreshold: {{ .Values.probes.readiness.successThreshold }}
        resources:
          {{ toYaml .Values.anchoreCatalog.resources | nindent 10 }}
      volumes:
        {{- if .Values.anchoreEnterpriseGlobal.enabled }}
        - name: anchore-license
          secret:
            secretName: {{ .Values.anchoreEnterpriseGlobal.licenseSecretName }}
        {{- end }}
        - name: config-volume
          configMap:
            name: {{ template "enterprise.fullname" . }}
        {{- if .Values.policyBundles }}
        - name: policy-bundle-volume
          configMap:
            name: {{ template "enterprise.fullname" . }}-policy-bundles
        {{- end }}
        {{- if .Values.openShiftDeployment }}
        - name: service-config-volume
          emptyDir: {}
        - name: logs
          emptyDir: {}
        - name: run
          emptyDir: {}
        {{- end }}
        {{- with .Values.certStoreSecretName }}
        - name: certs
          secret:
            secretName: {{ . }}
        {{- end }}
        {{- if .Values.cloudsql.useExistingServiceAcc }}
        - name: {{ .Values.cloudsql.serviceAccSecretName }}
          secret:
            secretName: {{ .Values.cloudsql.serviceAccSecretName }}
        {{- end }}
      {{- with .Values.anchoreCatalog.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.anchoreCatalog.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.anchoreCatalog.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serviceAccountName }}
      serviceAccountName: {{ . }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "enterprise.catalog.fullname" . }}
  labels:
    app: {{ template "enterprise.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ $component }}
    {{- with .Values.anchoreCatalog.service.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.anchoreCatalog.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.anchoreCatalog.service.type }}
  ports:
    - name: anchore-catalog-api
      port: {{ .Values.anchoreCatalog.service.port }}
      targetPort: {{ .Values.anchoreCatalog.service.port }}
      protocol: TCP
  selector:
    app: {{ template "enterprise.fullname" . }}
    component: {{ $component }}
