kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ template "enterprise.fullname" . }}-env"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "enterprise.labels" . | indent 4 }}
  annotations:
    {{- include "enterprise.annotations" . | indent 4 }}
data:
  ANCHORE_DB_NAME: {{ index .Values "postgresql" "postgresqlDatabase" | quote }}
  ANCHORE_DB_USER: {{ index .Values "postgresql" "postgreslqUser" | quote }}
{{- if and (index .Values "postgresql" "externalEndpoint") (not (index .Values "postgresql" "enabled")) }}
  ANCHORE_DB_HOST: {{ index .Values "postgresql" "externalEndpoint" | quote }}
{{- else if and (index .Values "cloudsql" "enabled") (not (index .Values "postgresql" "enabled")) }}
  ANCHORE_DB_HOST: "localhost:5432"
{{- else }}
  ANCHORE_DB_HOST: "{{ template "postgres.fullname" . }}:5432"
{{- end }}
