{{- if and .Values.anchoreEnterpriseGlobal.enabled .Values.feeds.enabled .Values.feedsUpgradeJob.enabled }}
{{- $component := "feedsUpgradeJob" -}}

apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-feeds-upgrade"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "enterprise.labels" (merge (dict "component" $component) .) | indent 4 }}
  annotations:
    {{- include "enterprise.annotations" (merge (dict "component" $component) .) | indent 4 }}
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-3"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-{{ .Chart.AppVersion }}-feeds-upgrade"
      labels:
        {{- include "enterprise.labels" (merge (dict "component" $component) .) | indent 8 }}
      annotations:
        {{- include "enterprise.annotations" (merge (dict "component" $component) .) | indent 8 }}
    spec:
    {{- with .Values.securityContext }}
      securityContext:
        {{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.serviceAccountName }}
      serviceAccountName: {{ . }}
    {{- end }}
    {{- with .Values.imagePullSecretName }}
      imagePullSecrets:
      - name: {{ . }}
    {{- end }}
      restartPolicy: Never
      containers:
      - name: "{{ .Release.Name }}-feeds-upgrade"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        image: {{ .Values.image }}
      {{- if .Values.dbConfig.ssl }}
        args: ["/bin/bash", "-c", "anchore-enterprise-manager db --db-use-ssl --db-connect postgresql://${ANCHORE_DB_USER}:${ANCHORE_FEEDS_DB_PASSWORD}@${ANCHORE_DB_HOST}/${ANCHORE_DB_NAME}?sslmode={{ .Values.dbConfig.sslMode }}\\&sslrootcert=/home/anchore/certs/{{ .Values.dbConfig.sslRootCertName }} upgrade --dontask"]
      {{- else }}
        args: ["/bin/bash", "-c", "anchore-enterprise-manager db --db-connect postgresql://${ANCHORE_DB_USER}:${ANCHORE_FEEDS_DB_PASSWORD}@${ANCHORE_DB_HOST}/${ANCHORE_DB_NAME} upgrade --dontask"]
      {{- end }}
        envFrom:
    {{- if not .Values.inject_secrets_via_env }}
      {{- if .Values.feeds.existingSecret }}
        - secretRef:
            name: {{ .Values.feeds.existingSecret }}
      {{- else }}
        - secretRef:
            name: {{ template "enterprise.feeds.fullname" . }}
        - secretRef:
            name: "{{ template "enterprise.fullname" . }}-admin-pass"
      {{- end }}
    {{- end }}
        - configMapRef:
            name: "{{ template "enterprise.feeds.fullname" . }}-env"
        env:
        {{- include "enterprise.environment" (merge (dict "component" $component) .) | indent 8 }}
      {{- if (.Values.certStoreSecretName) }}
        volumeMounts:
        - name: certs
          mountPath: /home/anchore/certs/
          readOnly: true
      {{- end }}
    {{- with .Values.certStoreSecretName }}
      volumes:
      - name: certs
        secret:
          secretName: {{ . }}
    {{- end }}
    {{- with .Values.feedsUpgradeJob.nodeSelector }}
      nodeSelector:
        {{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.feedsUpgradeJob.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.feedsUpgradeJob.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
    {{- end }}
{{- end -}}
