{{- if .Values.ui.enabled -}}
{{- $component := "ui" -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "enterprise.ui.fullname" . | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "enterprise.labels" (merge (dict "component" $component) .) | indent 4 }}
  annotations:
    {{- include "enterprise.annotations" (merge (dict "component" $component) .) | indent 4 }}
data:
  config-ui.yaml: |
    # Anchore UI configuration
  {{- if .Values.internalServicesSsl.enabled }}
    engine_uri: 'https://{{ template "enterprise.api.fullname" . }}:{{ .Values.api.service.port }}/v1'
  {{- else }}
    engine_uri: 'http://{{ template "enterprise.api.fullname" . }}:{{ .Values.api.service.port }}/v1'
  {{- end }}
    # This value is overridden by using the `ANCHORE_REDIS_URI` environment variable.
    # redis_ui: $ANCHORE_REDIS_URI
{{- if .Values.enableAnchoreRbac }}
  {{- if .Values.internalServicesSsl.enabled }}
    rbac_uri: 'https://{{ template "enterprise.api.fullname" . }}:{{ .Values.rbacManager.service.port }}/v1'
  {{- else }}
    rbac_uri: 'http://{{ template "enterprise.api.fullname" . }}:{{ .Values.rbacManager.service.port }}/v1'
  {{- end }}
{{- end }}
{{- if .Values.reports.enabled }}
  {{- if .Values.internalServicesSsl.enabled }}
    reports_uri: 'https://{{ template "enterprise.api.fullname" . }}:{{ .Values.reports.service.port}}/v1'
  {{- else}}
    reports_uri: 'http://{{ template "enterprise.api.fullname" . }}:{{ .Values.reports.service.port}}/v1'
  {{- end }}
{{- end }}
{{- if .Values.notifications.enabled }}
  {{- if .Values.internalServicesSsl.enabled }}
    notifications_uri: 'https://{{ template "enterprise.api.fullname" . }}:{{ .Values.notifications.service.port}}/v1'
  {{- else}}
    notifications_uri: 'http://{{ template "enterprise.api.fullname" . }}:{{ .Values.notifications.service.port}}/v1'
  {{- end }}
{{- end }}
    # This value is overridden by using the `ANCHORE_APPDB_URI` environment variable.
    # appdb_uri: $ANCHORE_APPDB_URI
    license_path: '/home/anchore/'
    enable_ssl: {{ .Values.ui.enableSsl }}
    enable_proxy: {{ .Values.ui.enableProxy }}
    allow_shared_login: {{ .Values.ui.enableSharedLogin }}
    redis_flushdb: {{ .Values.ui.redisFlushdb }}
  {{- with .Values.ui.customLinks }}
    custom_links:
      title: {{ .title }}
      links:
    {{- range .links }}
      {{- with . }}
        - title: {{ .title }}
          uri: {{ .uri }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- with .Values.ui.enableAddRepositories }}
    enable_add_repositories:
      admin: {{ .admin }}
      standard: {{ .standard }}
  {{- end }}

{{- end -}}
