{{- if .Values.ingress.enabled -}}
{{- $component := "ingress" -}}

apiVersion: {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }} networking.k8s.io/v1beta1 {{- else }} extensions/v1beta1 {{- end }}
kind: Ingress
metadata:
  name: {{ template "enterprise.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "enterprise.labels" (merge (dict "component" $component) .) | indent 4 }}
  annotations:
    {{- include "enterprise.annotations" (merge (dict "component" $component) .) | indent 4 }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- if or .Values.ingress.apiHosts .Values.ingress.uiHosts .Values.ingress.feedsHosts .Values.ingress.reportsHosts }}
    {{- range .Values.ingress.apiHosts }}
    - host: {{ . | quote }}
      http:
        paths:
        - path: {{ $.Values.ingress.apiPath }}
          backend:
            serviceName: {{ template "enterprise.api.fullname" $ }}
            servicePort: {{ $.Values.api.service.port }}
    {{- end }}
    {{- range .Values.ingress.uiHosts }}
    - host: {{ . | quote }}
      http:
        paths:
        - path: {{ $.Values.ingress.uiPath }}
          backend:
            serviceName: {{ template "enterprise.ui.fullname" $ }}
            servicePort: {{ $.Values.ui.service.port }}
    {{- end }}
    {{- range .Values.ingress.feedsHosts }}
    - host: {{ . | quote }}
      http:
        paths:
        - path: {{ $.Values.ingress.feedsPath }}
          backend:
            serviceName: {{ template "enterprise.feeds.fullname" $ }}
            servicePort: {{ $.Values.feeds.service.port }}
    {{- end }}
    {{- range .Values.ingress.reportsHosts }}
    - host: {{ . | quote }}
      http:
        paths:
        - path: {{ $.Values.ingress.reportsPath }}
          backend:
            serviceName: {{ template "enterprise.reports.fullname" $ }}
            servicePort: {{ $.Values.reports.service.port }}
    {{- end }}
  {{- else }}
    - http:
        paths:
        {{- with .Values.ingress.apiPath }}
        - path: {{ . }}
          backend:
            serviceName: {{ template "enterprise.api.fullname" $ }}
            servicePort: {{ $.Values.api.service.port }}
        {{- end }}
        {{- with .Values.ingress.uiPath }}
        - path: {{ . }}
          backend:
            serviceName: {{ template "enterprise.ui.fullname" $ }}
            servicePort: {{ $.Values.ui.service.port }}
        {{- end }}
        {{- with .Values.ingress.feedsPath }}
        - path: {{ . }}
          backend:
            serviceName: {{ template "enterprise.feeds.fullname" $ }}
            servicePort: {{ $.Values.feeds.service.port }}
        {{- end }}
        {{- with .Values.ingress.reportsPath }}
        - path: {{ . }}
          backend:
            serviceName: {{ template "enterprise.reports.fullname" $ }}
            servicePort: {{ $.Values.reports.service.port }}
        {{- end }}
  {{- end }}

{{- end -}}
