{{- if .Values.policyBundles }}
{{- $component := "policyEngine" -}}

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "enterprise.fullname" . }}-policy-bundles
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "enterprise.labels" (merge (dict "component" $component) .) | indent 4 }}
  annotations:
    {{- include "enterprise.annotations" (merge (dict "component" $component) .) | indent 4 }}
data:
{{- with .Values.policyBundles }}
{{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}