{{- if not .Values.ui.existingSecret }}
{{- if .Values.ui.enabled -}}
{{- $component := "ui" -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "enterprise.ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "enterprise.labels" (merge (dict "component" $component) .) | indent 4 }}
  annotations:
    {{- include "enterprise.annotations" (merge (dict "component" $component) .) | indent 4 }}
type: Opaque
stringData:
{{- if .Values.dbConfig.ssl }}
  ANCHORE_APPDB_URI: 'postgresql://{{ index .Values "postgresql" "postgresqlUsername" }}:{{ index .Values "postgresql" "postgresqlPassword" }}@{{ template "enterprise.db-hostname" . }}/{{ index .Values "postgresql" "postgresqlDatabase" }}?ssl=verify-full'
{{- else }}
  ANCHORE_APPDB_URI: 'postgresql://{{ index .Values "postgresql" "postgresqlUsername" }}:{{ index .Values "postgresql" "postgresqlPassword" }}@{{ template "enterprise.db-hostname" . }}/{{ index .Values "postgresql" "postgresqlDatabase" }}'
{{- end -}}

{{- if and (index .Values "anchore-ui-redis" "externalEndpoint") (not (index .Values "anchore-ui-redis" "enabled")) }}
  ANCHORE_REDIS_URI: '{{ index .Values "anchore-ui-redis" "externalEndpoint" }}'
{{- else }}
  ANCHORE_REDIS_URI: 'redis://nouser:{{ index .Values "anchore-ui-redis" "password" }}@{{ template "redis.fullname" . }}-master:6379'
{{- end -}}

{{- end -}}
{{- end -}}
