{{- if .Values.upgradeJob.enabled -}}
{{- $component := "upgradeJob" -}}

apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-upgrade"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "enterprise.labels" (merge (dict "component" $component) .) | indent 4 }}
  annotations:
    {{- include "enterprise.annotations" (merge (dict "component" $component) .) | indent 4 }}
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-{{ .Chart.AppVersion }}-upgrade"
      labels:
        {{- include "enterprise.labels" (merge (dict "component" $component) .) | indent 8 }}
      annotations:
        {{- include "enterprise.annotations" (merge (dict "component" $component) .) | indent 8 }}
    spec:
    {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.serviceAccountName }}
      serviceAccountName: {{ . }}
    {{- end }}
    {{- with .Values.imagePullSecretName }}
      imagePullSecrets:
      - name: {{ . }}
    {{- end }}
      restartPolicy: Never
      containers:
      - name: "{{ .Release.Name }}-upgrade"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        image: {{ .Values.image }}
      {{- if .Values.dbConfig.ssl }}
        args: ["/bin/bash", "-c", "anchore-enterprise-manager db --db-use-ssl --db-connect postgresql://${ANCHORE_DB_USER}:${ANCHORE_DB_PASSWORD}@${ANCHORE_DB_HOST}/${ANCHORE_DB_NAME}?sslmode={{ .Values.dbConfig.sslMode }}\\&sslrootcert=/home/anchore/certs/{{ .Values.dbConfig.sslRootCertName }} upgrade --dontask"]
      {{- else }}
        args: ["/bin/bash", "-c", "anchore-enterprise-manager db --db-connect postgresql://${ANCHORE_DB_USER}:${ANCHORE_DB_PASSWORD}@${ANCHORE_DB_HOST}/${ANCHORE_DB_NAME} upgrade --dontask"]
      {{- end }}
    {{- if not .Values.inject_secrets_via_env }}
        envFrom:
      {{- if .Values.existingSecret }}
        - secretRef:
            name: {{ .Values.existingSecret }}
      {{- else }}
        - secretRef:
            name: {{ template "enterprise.fullname" . }}
        - secretRef:
            name: "{{ template "enterprise.fullname" .}}-admin-pass"
      {{- end }}
    {{- end }}
        env:
        {{- include "enterprise.environment" (merge (dict "component" $component) .) | indent 8 }}
        {{- include "enterprise.engineDbConfigEnv" . | nindent 8 }}
      {{- if (.Values.certStoreSecretName) }}
        volumeMounts:
        - name: certs
          mountPath: /home/anchore/certs/
          readOnly: true
      {{- end }}
    {{- with .Values.certStoreSecretName }}
      volumes:
      - name: certs
        secret:
          secretName: {{ . }}
    {{- end }}
    {{- with .Values.upgradeJob.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.upgradeJob.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.upgradeJob.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

{{- end -}}