name: "Test using kind and chart-testing tool"

on:
  - pull_request
  push:
    branches:
      - 'dev/devops-206'
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        kubernetesVersion: ["v1.14.10", "v1.22.0"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fetch history
      run: git fetch --prune --unshallow

    - name: Shellcheck
      uses: ludeeus/action-shellcheck@1.0.0

    - name: Run chart-testing (lint)
      id: lint
      uses: helm/chart-testing-action@v1.1.0
      with:
        command: lint
        config: ct-config.yaml

    - name: Install kind
      uses: helm/kind-action@v1.2.0
      with:
        node_image: "kindest/node:${{ matrix.kubernetesVersion }}"
        config: kind-config.yaml
        wait: 600s
      if: steps.lint.outputs.changed == 'true'

    - name: Check kind nodes
      run: kubectl describe nodes

    - name: Run chart-testing (install)
      uses: helm/chart-testing-action@v1.1.0
      with:
        command: install
        config: ct-config.yaml
